name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: install
      run : npm install
    - name: build
      run : npm run build
    - name: Build and Deploy
      uses: avinal/github-pages-deploy-action@main
      env:
        ACCESS_TOKEN: ${{ secrets.PRJ_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build